source("/Volumes/zmliu_02/PPiseq/DMSO/all_lintag_files_final/R_code/function.R") # load commonly used functions
apple_colors = c("#5AC8FA", "#FFCC00", "#FF9500", "#FF2D55", "#007AFF", "#4CD964", "#FF3B30",
                 "#8E8E93", "#EFEFF4", "#CECED2", "#000000", "007AFF")

####################### (1) Combine different time points and make lineage trajectories
setwd("/Volumes/zmliu_02/PPiseq/DMSO/counts/")
T0= "G0_all_PPIcounts.csv"
T3= "G3_all_PPIcounts.csv"
T6= "G6_all_PPIcounts.csv"
T9= "G9_all_PPIcounts.csv"
T12= "G12_all_PPIcounts.csv"
lineage= "lineage_trajectories.csv"
lineage_combine(T0, T3, T6, T9, T12, lineage)

# Check barcode counts at each time point
G0 = dataFrameReader_T("G0_all_PPIcounts.csv")
G3 = dataFrameReader_T("G3_all_PPIcounts.csv")
G6 = dataFrameReader_T("G6_all_PPIcounts.csv")
G9 = dataFrameReader_T("G9_all_PPIcounts.csv")
G12 = dataFrameReader_T("G12_all_PPIcounts.csv")
nrow(G0) # 6185226
sum(G0[,2]) # 276456005
sum(G0[,3]) # 209899687

nrow(G3) # 6202462
sum(G3[,2]) # 261007466
sum(G3[,3]) # 216347783

nrow(G6) # 6186372
sum(G6[,2]) # 270112626
sum(G6[,3]) # 251280599

nrow(G9) # 5414141
sum(G9[,2]) # 237323399
sum(G9[,3]) # 211386857

nrow(G12) # 4027729
sum(G12[,2]) # 213627166
sum(G12[,3]) # 201043159

####################### (2) Correct the barcode counts based on the single barcode frequencies
setwd("/Volumes/zmliu_02/PPiseq/DMSO/counts/")
lineage_barcodes= "lineage_trajectories.csv" # input file
lineage_combine = csvReader_T(lineage_barcodes)
DBC_split = split_string_vector(lineage_combine[,1])
BC1_unique = unique(DBC_split[,1]) #2586
BC2_unique = unique(DBC_split[,2]) #3835
BC1_unique_matrix = matrix(0, length(BC1_unique), 6)
BC1_unique_matrix[,1] = BC1_unique
BC2_unique_matrix = matrix(0, length(BC2_unique), 6)
BC2_unique_matrix[,1] = BC2_unique 
# Get counts for each of unique BC1 at each time point
for(i in 1:length(BC1_unique)){
        a = which(DBC_split[,1] == BC1_unique[i])
        for(j in 2:6){
                BC1_unique_matrix[i,j] = sum(as.numeric(lineage_combine[a,j]))
        }
}
# Get counts for each of unique BC2 at each time point
for(i in 1:length(BC2_unique)){
        a = which(DBC_split[,2] == BC2_unique[i])
        for(j in 2:6){
                BC2_unique_matrix[i,j] = sum(as.numeric(lineage_combine[a,j]))
        }
}
colnames(BC1_unique_matrix) = c("BC1", "G0", "G3", "G6", "G9", "G12")
colnames(BC2_unique_matrix) = c("BC2", "G0", "G3", "G6", "G9", "G12")
csvWriter(BC1_unique_matrix, "BC1_unique_counts.csv")
csvWriter(BC2_unique_matrix, "BC2_unique_counts.csv")

# Input all the pairwise mated DBC strains (Positive, negative, PRS, RRS)
DBC_pairwise = csvReader_T("/Volumes/zmliu_02/PPiseq/DMSO/all_lintag_files_final/PPI_barcodes/pairwise_barcodes.csv")
constant_barcodes = split_string_vector(DBC_pairwise[,3])

# Tease out these barcodes generated by PCR chimera
wrong_DBC_counts = rep(0, 6)
for(i in 1:nrow(constant_barcodes)){
        a = which(DBC_split[,1] == constant_barcodes[i,1] & DBC_split[,2] != constant_barcodes[i,2])
        b = which(DBC_split[,1] != constant_barcodes[i,1] & DBC_split[,2] == constant_barcodes[i,2])
        m= unique(c(a,b))
        wrong_DBC_counts= rbind(wrong_DBC_counts, lineage_combine[m,])
}

wrong_DBC_counts= wrong_DBC_counts[2:nrow(wrong_DBC_counts),] #1469624
colnames(wrong_DBC_counts) = c("DBC", "G0", "G3", "G6", "G9", "G12")
wrong_DBC_counts_unique = wrong_DBC_counts[which(!duplicated(wrong_DBC_counts)),] # 378026
wrong_DBC_counts_final = wrong_DBC_counts_unique[which(!wrong_DBC_counts_unique[,1] %in% DBC_pairwise[,3]),] # 377125
csvWriter(wrong_DBC_counts_final, "Wrong_DBC_counts.csv")


# plot wrong_DBC_counts vs the products of the corresponding two single barcode counts
wrong_DBC = csvReader_T("Wrong_DBC_counts.csv")
BC1_unique = csvReader_T("BC1_unique_counts.csv")
BC2_unique = csvReader_T("BC2_unique_counts.csv")
unmatched_DBC = dataFrameReader_T("Unmatched_barcode_lineages.csv") #377138
length(which(wrong_DBC[,1] %in% unmatched_DBC[,1])) # 377125
nrow(wrong_DBC) # 377125

plot_name = c("a", "correction/G0_PCR_chimera.pdf", "correction/G3_PCR_chimera.pdf", "correction/G6_PCR_chimera.pdf",
              "correction/G9_PCR_chimera.pdf", "correction/G12_PCR_chimera.pdf")
for(i in 2:6){
        DBC_counts = as.numeric(wrong_DBC[,i])
        DBC_barcode = split_string_vector(wrong_DBC[,1])
        SBC_product = rep(0, length(DBC_counts))
        for(j in 1:length(DBC_counts)){
                m = as.numeric(BC1_unique[which(BC1_unique[,1] == DBC_barcode[j,1]), i])  
                n = as.numeric(BC2_unique[which(BC2_unique[,1] == DBC_barcode[j,2]), i])
                SBC_product[j] = m * n
        }
        pdf(plot_name[i], width= 5, height = 5)
        plot(SBC_product, DBC_counts, xlab = "BC1 * BC2 counts",
             ylab= "BC1-BC2 counts", type = "p", cex =0.6, col = rgb(0,0,1,alpha=0.3))
        dev.off()
}

# All the plot show linear relationship between BC1-BC2 counts and BC1*BC2 counts, 
# Linear regression to show the equation at each time point
correct_slope = rep(0,5)
for(i in 2:6){
        DBC_counts = as.numeric(wrong_DBC[,i])
        DBC_barcode = split_string_vector(wrong_DBC[,1])
        SBC_product = rep(0, length(DBC_counts))
        for(j in 1:length(DBC_counts)){
                m = as.numeric(BC1_unique[which(BC1_unique[,1] == DBC_barcode[j,1]), i])  
                n = as.numeric(BC2_unique[which(BC2_unique[,1] == DBC_barcode[j,2]), i])
                SBC_product[j] = m * n
        }
        correct_slope[i-1] = lm(DBC_counts ~ SBC_product - 1)$coefficient
}
correct_slope_matrix = rbind(c("G0", "G3", "G6", "G9", "G12"), correct_slope)
csvWriter(correct_slope_matrix, "correction/corrected_slope_all_time_points.csv")

# Correct the the counts
lineage_counts = csvReader_T("lineage_trajectories.csv")
lineage_counts_correct = matrix(0, nrow(lineage_counts), ncol(lineage_counts))
lineage_counts_correct[,1] = lineage_counts[,1]

for(i in 1:nrow(lineage_counts)){
        barcode = lineage_counts[i,1]
        barcode_split = split_string_vector(barcode)
        m = as.numeric(BC1_unique[which(BC1_unique[,1] == barcode_split[1]), 2:6])  
        n = as.numeric(BC2_unique[which(BC2_unique[,1] == barcode_split[2]), 2:6])
        product = m * n * correct_slope
        lineage_counts_correct[i,2:6] = as.numeric(round(as.numeric(lineage_counts[i, 2:6]) - product, digits = 0))
}
colnames(lineage_counts_correct) = colnames(lineage_counts)
csvWriter(lineage_counts_correct, "lineage_trajectories_corrected.csv")

####################### (3) Match the double barcode clustering results to known barcodes (exact match)
lineage_combine= csvReader_T("lineage_trajectories_corrected.csv") #6855881
PPI_barcodes_all = csvReader_T("/Volumes/zmliu_02/PPiseq/DMSO/all_lintag_files_final/PPI_barcodes/PPiseq_all_barcodes.csv")

DBC_known_counts = barcodes_match_PPI(lineage_combine, PPI_barcodes_all)# 6478743
colnames(DBC_known_counts)= c("Systematic_PPI", "Standard_PPI", "barcode", "G0", "G3", "G6", "G9", "G12")
csvWriter(DBC_known_counts, "known_PPI_barcodes_counts.csv")

unmatched_DBC = lineage_combine[which(!lineage_combine[,1] %in% DBC_known_counts[,3]),] # 377138
csvWriter(unmatched_DBC, "Unmatched_barcode_lineages.csv")

unmatched_PPI_barcodes = PPI_barcodes_all[which(!PPI_barcodes_all[,3] %in% DBC_known_counts[,3]),] # 1262338
csvWriter(unmatched_PPI_barcodes, "Unmatched_PPI_barcode.csv")

DBC_known_counts = csvReader_T("known_PPI_barcodes_counts.csv")
# make sure the minimum of DBC_known_counts == 0
for (i in 1:nrow(DBC_known_counts)){
        a = as.numeric(DBC_known_counts[i,4:8])
        a[which(a <= 0)] = 0
        DBC_known_counts[i, 4:8] = a
}
matched_DBC_sum = rep(0,5)
for(i in 1:5){
        matched_DBC_sum[i] = sum(as.numeric(DBC_known_counts[,i + 3]))
}
matched_DBC_sum # 193923012; G3: 201150732; G6: 226655124; G9: 193734810; G12: 185972666

# filter out bad lineages ( <= 2 time points counts > 0, or maximum of each time point <= 5 or total counts of a lineage < 10)
bad_index = rep(0, nrow(DBC_known_counts))
for(i in 1:length(bad_index)){
        counts = as.numeric(DBC_known_counts[i, 4:8])
        if (length(which(counts != 0)) < 3 | max(counts) < 5 | sum(counts) < 10){
                bad_index[i] = 1
        }
}

length(which(bad_index == 1)) # 1447775

good_lineages = DBC_known_counts[which(bad_index != 1),] 
csvWriter(good_lineages, "Good_lineage_trajectories_new.csv")

# Merge all bad lineages into one lineage by summin their counts at each time point
bad_lineages = DBC_known_counts[which(bad_index == 1),] ## 1392048
sum_bad_lineages = rep(0, 5)
for(i in 1:5){
        sum_bad_lineages[i] = sum(as.numeric(bad_lineages[,i + 3]))
}
sum_bad_lineages_final = c("Sum_bad_lineages", "Sum_bad_lineages", "Sum_bad_lineages", sum_bad_lineages)
good_lineages_final = rbind(good_lineages, sum_bad_lineages_final)
csvWriter(good_lineages_final, "Good_lineage_trajectories_add_sum_new.csv")

####################### (4) Calculate the fitness for all the lineages (matched to PPIs) (Fit-seq)
