
source("/Volumes/zmliu_02/PPiseq/HU/R_code/function.R")
apple_colors = c("#5AC8FA", "#FFCC00", "#FF9500", "#FF2D55", "#007AFF", "#4CD964", "#FF3B30",
                 "#8E8E93", "#EFEFF4", "#CECED2", "#000000", "007AFF")

# This script generate reference sets based on BioGRID and call PPIs in each environment

yeast_PPI = read.delim("/Volumes/zmliu_02/PPiseq/DMSO_2/reference_set/BIOGRID-ORGANISM-3.5.165.tab2/BIOGRID-ORGANISM-Saccharomyces_cerevisiae_S288c-3.5.165.tab2.txt", header = T)
pos_PPI= yeast_PPI[which(yeast_PPI$Experimental.System.Type == "physical"), c(6:7, 13)] # 164992
# generate positive PPIs with two directions (bait-prey or prey-bait)
pos_PPI_01= paste(pos_PPI[,1], pos_PPI[,2], sep="_")
pos_PPI_02= paste(pos_PPI[,2], pos_PPI[,1], sep="_")
pos_PPI_both= unique(c(pos_PPI_01, pos_PPI_02)) # 215884

### Gene included in PCA collection
yeast_gene= as.matrix(read.csv('/Volumes/zmliu_02/PPiseq/DMSO/all_lintag_files_final/reference_set/Yeast_genes.csv', header = F)) # PCA library doe not contain all the genes
yeast_PPI= expand.grid(yeast_gene[,1], yeast_gene[,1])# 32,216,976 two directions
yeast_PPI_filtered = yeast_PPI[which(yeast_PPI$Var1 != yeast_PPI$Var2),] # 32211300, remove sefl-interacting PPIs
All_PPI= paste(yeast_PPI_filtered[,1], yeast_PPI_filtered[,2], sep="_")
all_PPI_filtered = All_PPI[which(!All_PPI %in% pos_PPI_both)] #  32009066 filter the positive PPIs (193364)

### PPI summary generated by BioGRID
PPI_summary = dataFrameReader_T("/Volumes/zmliu_02/PPiseq/H2O2/reference_set/one_binary/multiple_validated_PPI.csv")

generating_reference_sets = function(all_PPI_filtered, PPI_summary, PPI_multiple, 
                                     number_PPI, sample_number, data_set_number){
        Random_reference <- function(PPI_multiple, all_PPI_filtered, size, sampling_number){
          PPI_PPiseq = PPI_multiple[,1]
          RRS_size= 0
          RRS= character(length=0)
          while (RRS_size < size) {
            yeast_PPI_random= all_PPI_filtered[sample(1: length(all_PPI_filtered), sampling_number, replace=F)]
            RRS= unique(c(RRS, yeast_PPI_random))
            RRS_overlap= intersect(RRS, PPI_PPiseq)
            RRS_size= length(RRS_overlap)
          } 
          RRS_duplicate_marked = mark_duplicates_fast(RRS_overlap)
          return (RRS_duplicate_marked[,1])
        }
        
        Random_reference_generation = function(PPI_multiple, all_PPI_filtered, number_PPI, sample_number, data_set_number){
          neg_set = vector("list", data_set_number)
          for(i in 1:data_set_number){
            PPI_neg = Random_reference(PPI_multiple, all_PPI_filtered, number_PPI, sample_number)
            PPI_neg_matrix = PPI_multiple[which(PPI_multiple[,1] %in% PPI_neg),]
            neg_set[[i]] = PPI_neg_matrix
          }
          return (neg_set)
        }
        
        PPI_3_assay= PPI_summary[which(PPI_summary$methods >= 3 & PPI_summary$publications >= 3 & PPI_summary$Binary_assy == 1),1] # 1968
        PPI_pos_3_assay = match_both_direction(PPI_multiple, PPI_3_assay) # 580
        print(nrow(PPI_pos_3_assay))
        pos_set = list(PPI_pos_3_assay)
        csvWriter(PPI_pos_3_assay[,1], "Positive_reference_set.csv")
        
        neg_set = Random_reference_generation (PPI_multiple, all_PPI_filtered, number_PPI, sample_number, data_set_number)
        
        pos_name = "PPI_pos_3_assay"
        neg_name = vector("character", data_set_number)
        for (i in 1:length(neg_name)){
          neg_name[i] = paste("neg", as.character(number_PPI), as.character(i), sep = "_")
        }
        
        for (i in 1:length(pos_set)){
          for (j in 1:length(neg_set)){
            a = as.matrix(pos_set[[i]])
            b = as.matrix(neg_set[[j]])
            csvWriter(b[,1], paste(neg_name[j],"reference.csv", sep = "_"))
            matrix = rbind(a,b)
            matrix[1:nrow(a), 1] = "Positive"
            matrix[(nrow(a) +1): (nrow(a) + nrow(b)), 1] = "Negative"
            colnames(matrix) = colnames(PPI_multiple)
            csvWriter(matrix, paste(pos_name[i], neg_name[j],"reference.csv", sep= "_"))
          }
        }
}

# DMSO
setwd("/Volumes/zmliu_02/PPiseq_03/DMSO/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/DMSO/counts/PPI_multiple_p.values.csv") 

generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 580

# DMSO_2
setwd("/Volumes/zmliu_02/PPiseq_03/DMSO_2/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/DMSO_2/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 586

# H2O2
setwd("/Volumes/zmliu_02/PPiseq_03/H2O2/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/H2O2/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 585

# HU
setwd("/Volumes/zmliu_02/PPiseq_03/HU/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/HU/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 576

# Dox
setwd("/Volumes/zmliu_02/PPiseq_03/Dox/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/Dox/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 561

# FK506
setwd("/Volumes/zmliu_02/PPiseq_03/FK506/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/FK506/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 517

# Raffinose
setwd("/Volumes/zmliu_02/PPiseq_03/Raffinose/reference_set/p_value/")
number_PPI = 4.5e4
sample_number = 4.5e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/Raffinose/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 432

# Forskolin
setwd("/Volumes/zmliu_02/PPiseq_03/Forskolin/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/Forskolin/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 534

# NaCl
setwd("/Volumes/zmliu_02/PPiseq_03/NaCl_0.4M/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/NaCl_0.4M/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 563

# 16C
setwd("/Volumes/zmliu_02/PPiseq_03/16C/reference_set/p_value/")
number_PPI = 6e4
sample_number = 6e4
data_set_number = 50
PPI_multiple = dataFrameReader_T("/Volumes/zmliu_02/PPiseq_03/16C/counts/PPI_multiple_p.values.csv") 
generating_reference_sets(all_PPI_filtered, PPI_summary, PPI_multiple, number_PPI, sample_number, data_set_number)
#Positive: 578
